//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.23 at 04:14:46 AM CEST 
//


package cars;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cars package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cars_QNAME = new QName("", "cars");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cars
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarsType }
     * 
     */
    public CarsType createCarsType() {
        return new CarsType();
    }

    /**
     * Create an instance of {@link ConsumptionType }
     * 
     */
    public ConsumptionType createConsumptionType() {
        return new ConsumptionType();
    }

    /**
     * Create an instance of {@link CarType }
     * 
     */
    public CarType createCarType() {
        return new CarType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CarsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CarsType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "cars")
    public JAXBElement<CarsType> createCars(CarsType value) {
        return new JAXBElement<CarsType>(_Cars_QNAME, CarsType.class, null, value);
    }

}
